name: auto-ssh-key test
on: push

jobs:
  # Label of the runner job
  runner-job:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      ssh-server:
        image: linuxserver/openssh-server
        env:
          PASSWORD_ACCESS: true
          USER_PASSWORD: password2
          USER_NAME: test_user
        ports:
          - 12222:2222

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y sshpass

      - name: Change script permissions
        run: chmod +x ./auto-ssh-key.sh
      
      - name: Run script
        run: echo password | ./auto-ssh-key.sh -u test_user -p -i localhost -s 12222